version: "3.9"

services:
  immich_downloader:
    build:
      context: .
      dockerfile: Dockerfile
#    image: thehelpfulidiot/immich-dl:latest
    container_name: immich_downloader
    environment:
      IMMICH_URL: "immich-url" #necessary
      API_KEY: "api-key" #necessary
      TOTAL_IMAGES_TO_DOWNLOAD: 20 #necessary
      PERSON_IDS: '["person-id-1", "person-id-2"]'
      ALBUM_IDS: '["album-id-1", "album-id-2"]' #optional, will pull from whole library if album_id and person_id are blank
      MIN_MEGAPIXELS: 2.0 #optional, no default
      MIN_WIDTH: 1000 #optional, no default
      MIN_HEIGHT: 800 #optional, no default
      SCREENSHOT_DIMENSIONS: '[[1170, 2532], [1920, 1080]]' #optional, no default
      OVERRIDE: "true" #default as shown
      MAX_PARALLEL_DOWNLOADS: 5 #default as shown
      DRY_RUN: "false" #default as shown
      ENABLE_HEIC_CONVERSION: "true" #default as shown
      MIN_DATE: "2020-01-01" #optional, Minimum date in YYYY-MM-DD format
      MAX_DATE: "2025-01-01" #optional, Maximum date in YYYY-MM-DD format
    volumes:
      - ./downloads:/downloads # OUTPUT_DIR set to /downloads in Dockerfile since the volume mapping is all that matters, but could be modified with env variables
